apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcore-871
  namespace: default 
  labels:
    k8s-app: wcore-871
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: wcore-871
  template:
    metadata:
      name: wcore-871
      labels:
        k8s-app: wcore-871
    spec:
      containers:
        - name: wcore-871
          image: 'tesch75/webcore:dev'
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---		
apiVersion: v1
kind: Service
metadata:
  name:  wcore-871
spec:
  selector:
    k8s-app: wcore-871
  type:  NodePort
  ports:  
   - port:  10871
     targetPort:  80
     nodePort:  31871
