apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcore-dev
  namespace: webcore-dev 
  labels:
    k8s-app: wcore-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: wcore-dev
  template:
    metadata:
      name: wcore-dev
      labels:
        k8s-app: wcore-dev
    spec:
      containers:
        - name: wcore-dev
          image: 'tesch75/webcore-dev:v1'
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---		
apiVersion: v1
kind: Service
metadata:
  name:  wcore-dev
  namespace: webcore-dev
spec:
  selector:
    k8s-app: wcore-dev
  type:  NodePort
  ports:  
   - port:  10801
     targetPort:  80
     nodePort:  31801
